---

- name: Install Git
  become: true
  tags: [install]
  apt: name=git state=present

- git_config:
    name: user.email
    value: egal
    scope: global

- git_config:
    name: user.name
    value: bstachmann
    scope: global

- git_config:
    name: merge.conflictstyle
    value: diff3
    scope: global

- name: Install htop
  become: true
  tags: [install]
  apt: name=htop state=present

- name: Install screen
  become: true
  tags: [install]
  apt: name=screen state=present

- name: Install VI Improved
  become: true
  tags: [install]
  apt: name=vim state=present

- name: Add package source for Atom Editor
  become: true
  tags: [configure]
  apt_repository: repo='ppa:webupd8team/atom' state=present

- name: Install Atom Editor
  become: true
  tags: [install]
  apt: name=atom state=present

- name: Add some extension to .bashrc
  tags: [configure]
  blockinfile:
    dest: ~/.bashrc
    block: |
      echo
      echo Welcome to UBUNTU-DEV
      echo - Activating VI mode for bash
      set -o vi
      echo - Use VIM as default editor.
      export EDITOR=vim
      if [ -d work ]
        then
        echo - Entering 'work' directory
        cd work
      fi
