---

- name: Install Git
  become: true
  apt: name=git-all state=present

- name: Install tig
  become: true
  apt: name=tig state=present

- name: Install htop
  become: true
  apt: name=htop state=present

- name: Install screen
  become: true
  apt: name=screen state=present

- name: Install VI Improved
  become: true
  apt: name=vim state=present

- name: Add package source for Atom Editor
  become: true
  apt_repository: repo='ppa:webupd8team/atom' state=present

- name: Install Atom Editor
  become: true
  apt: name=atom state=present

- name: Add some extension to .bashrc
  blockinfile:
    dest: ~/.bashrc
    block: |
      echo
      echo Welcome to UBUNTU-DEV
      echo - Activating VI mode for bash
      set -o vi

      if [ -d work ]
        then
        echo - Entering 'work' directory
        cd work
      fi
  tags:
    - configuration
