---

- name: Install Git
  become: true
  tags: [install]
  apt: name=git-all state=present

- name: Install tig
  become: true
  tags: [install]
  apt: name=tig state=present

- name: Install htop
  become: true
  tags: [install]
  apt: name=htop state=present

- name: Install screen
  become: true
  tags: [install]
  apt: name=screen state=present

- name: Install VI Improved
  become: true
  tags: [install]
  apt: name=vim state=present

- name: Add package source for Atom Editor
  become: true
  tags: [configure]
  apt_repository: repo='ppa:webupd8team/atom' state=present

- name: Install Atom Editor
  become: true
  tags: [install]
  apt: name=atom state=present

- name: Add some extension to .bashrc
  tags: [configure]
  blockinfile:
    dest: ~/.bashrc
    block: |
      echo
      echo Welcome to UBUNTU-DEV
      echo - Activating VI mode for bash
      set -o vi
      echo - Use VIM as default editor.
      export EDITOR=vim
      echo - Using UI on display :0
      export DISPLAY=:0
      if [ -d work ]
        then
        echo - Entering 'work' directory
        cd work
      fi
