---
- hosts: localhost

  vars_files:
    - ~/.ubuntu-dev-vars.yml

  roles:
    - setup
    - development-tools
    - atom-editor
    - blogging
    - elm-programming
    - intellij-idea-community
    - kotlin
    - role: ansible-role-atom-packages
      atom_packages_packages:
       - language-elm
       - elmjutsu
      tags: [install]
#    - writer-tools
#    - photo-tools
