---
- hosts: localhost
  remote_user: bjoern
  sudo: yes

  tasks:

  - name: Allow VirtualBox Shared Folder Access for User Bjoern
    user: name=bjoern group=vboxsf

  - name: Install VI Improved
    apt: name=vim state=present

  - name: Link working directory
    file: src=/media/sf_work dest=/home/bjoern/work state=link

  - name: Add package source for Atom Editor
    apt_repository: repo='ppa:webupd8team/atom' state=present

  - name: Install Atom Editor
    apt: name=atom state=present

  - name: Install TeXLive
    apt: name=texlive-full state=present
