---
- hosts: localhost

  vars_files:
    - ~/.ubuntu-dev-vars.yml

  roles:
#    - setup
#    - development-tools
    - elm-programming
    - role: ansible-role-atom-packages
      atom_packages_packages:
        - language-elm
        - elmjutsu
      tags: [install]
#    - writer-tools
#    - photo-tools
