---
- hosts: localhost

  vars_files:
    - ~/.ubuntu-dev-vars.yml

  roles:
    - setup
    - development-tools
    - role: ansible-role-atom-packages
      atom_packages_packages:
        - language-elm
      tags: [install]
#    - writer-tools
#    - photo-tools
