---
- hosts: localhost
  remote_user: bjoern
  sudo: yes

  tasks:

  - name: Install TeXLive
    apt: name=texlive-full state=present

  - name: Install Digikam
    apt: name=digikam state=present

  roles:
    - setup
    - development-tools
    - role: ansible-role-atom-packages
      sudo: no
      atom_packages_packages: 'language-elm'
