---
- hosts: localhost

  vars_files:
    # - vault/vault.yml
    - group_vars/vars.yml
    - ~/.user_vault.yml

  remote_user: "{{dev_user}}"

  roles:
    - setup
    - development-tools
    - role: ansible-role-atom-packages
#      become: false
      atom_packages_packages:
        - language-elm
    - writer-tools
    - photo-tools
