---
- hosts: localhost

  vars_files:
    # - vault/vault.yml
    - group_vars/vars.yml
    - ~/.user_vault.yml

  remote_user: "{{dev_user}}"

  tasks:

    - name: Echo
      debug: var=dev_user

    - name: Install TeXLive
      apt: name=texlive-full state=present
      become: true

    - name: Install Digikam
      apt: name=digikam state=present
      become: true

  roles:
    - setup
    - development-tools
    - role: ansible-role-atom-packages
#      become: false
      atom_packages_packages:
        - language-elm
