---
- name: Print some interesting vars
  debug: var=ubuntu_dev_become_pass

- name: Configure ansible roles dir.
  tags: [configure]
  become: true
  lineinfile: dest=/etc/ansible/ansible.cfg regexp="^#?roles_path=" line="roles_path=/home/{{ansible_user_id}}/ansible-roles"

- name: Install SSH
  become: true
  tags: [install]
  apt: name=openssh-server state=present

- name: SSH key für user hochladen
  tags: [configure]
  authorized_key: user="{{ansible_user_id}}" key="{{user_public_key}}"

#- name: Configure Screen Saver not lock. (This is meant to run in a VM, so the host will lock)
#  tags: [configure]
#  copy: src=xfce4-power-manager.xml dest=~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
  #- name: Configure Screen Saver not lock. (This is meant to run in a VM, so the host will lock)
  #tags: [configure]
  #copy: src=xfce4-power-manager.xml dest=~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
