---
- name: Print some interesting vars
  debug: var=dev_user

- name: Configure ansible roles dir.
  lineinfile: dest=/etc/ansible/ansible.cfg regexp="^#?roles_path=" line="roles_path=/home/{{ansible_user}}/ansible-roles"
  become: true

- name: Install SSH
  apt: name=openssh-server state=present
